### ISSUE TITLE
[1 Minute Share] 24.11.02.

### ISSUE THREAD

**Issue by boonghoho** [Team-UEMO/No-Got-It#3]
- 넷마블 네오 코테 준비 (넥토리얼 코테보다는 더 잘보고 싶다)
- 언리얼 멀티플레이 tps 게임 총 쏘는 것 까지 구현

- 누구나 만들 수 있는 그럴싸한 컨텐츠들로 구성된 게임보다는 개발자로서의 파고들 수 있는 주제를 정해서 기술적 어려움과 해결과정을 보여줄 수 있는 게임을 만드는 것이 좋아 보인다고 말해줬다는 글을 보았음. 뭔가 개발자로서 파고들 수 있는 주제를 하나 정해서 프로젝트에 넣을 것 생각하기.

**Comment by uowol** [comment]
- 논문 리뷰 및 구현 : Deciphering Cross-Modal Alignment in Large Vision-Language Models with Modality Integration Rate
- 알고리즘 하나 :D
