### ISSUE TITLE
[1 Minute Share] 24.12.01.

### ISSUE THREAD

**Issue by aor9** [Team-UEMO/No-Got-It#8]
이번 주 한 일을 공유합니다.

일정 : 12월 01일 오후 2시 ~

**Comment by aor9** [comment]
- 매일 알고리즘 풀었음
- TPS게임 게임 타이머, 힐 아이템 만들었음
- effective c++ 조금 읽었음
- 그래픽스 6강까지 들었음
- 펄어비스 인턴십 서류 합격해서 인적성 시험 봤음 (필기 테스트 준비중)

**Comment by uowol** [comment]
- 프로토타입 개발
- 예비군 잘 댕기옴
- 한 달 계획 작성 (https://www.notion.so/uowon/12-14ff4a100a6180a3ac6ac9ba1846c776?pvs=4)
- 현대카드 코딩테스트 (후기: https://www.notion.so/uowon/14ff4a100a61800ab42dc63929ac22ae?pvs=4)
